### ISSUE TITLE
Conditional links

### ISSUE THREAD

**Issue by useo6** [robin1liu/vue-mermaid#11]
I need to create a link with different text to different nodes, e.g.:

![mermaid-diagram-20191229114815](https://user-images.githubusercontent.com/13544117/71555895-35a52180-2a31-11ea-86bb-49ba88fdeda8.png)

I tried using multiple links like this:

>       nodes: [
>         {
>           id: "1",
>           text: "A",
>           link: ["-- yes -->", "-- no -->"],
>           next: ["2", "3"],
>           editable: true
>         },
>         { id: "2", text: "B", next: ["4"], editable: true },
>         { id: "3", text: "C", next: ["4"], editable: true },
>         { id: "4", text: "D"},
>       ],

Unfortunately this creates something like this:

![mermaid](https://user-images.githubusercontent.com/13544117/71555929-c3810c80-2a31-11ea-95a9-a7e3482c17f8.png)

Any idea?

**Comment by robin1liu** [comment]
nodes: [
        {
          id: "1",
          text: "A",
          link: "-- yes -->",
          next: ["2"],
          editable: true
        },
        {
          id: "1",
          text: "A",
          link: "-- no -->",
          next: [ "3"],
          editable: true
        },
        { id: "2", text: "B", next: ["4"], editable: true },
        { id: "3", text: "C", next: ["4"], editable: true },
        { id: "4", text: "D" }
      ]

**Comment by robin1liu** [comment]
same issue as #2

**Comment by robin1liu** [comment]
add support at version 0.0.12

**Comment by foobst** [comment]
I had the same issue and used the solution using a separate entry in the nodes array, but... it was only a work around. Now, I updated to version 0.0.12 to see if I can replace my workaround but I unfortunately 0.0.12 doesn't fix the problem... the problem still exists as described by useo6. I get the same result as with version 0.0.11:

![grafik](https://user-images.githubusercontent.com/38371251/71559802-bdefea80-2a62-11ea-8a85-d7c61cd41f41.png)

Here's my package.json:

>   "dependencies": {
>     "mermaid": "8.4.4",
>     "vue-mermaid": "0.0.12"
>   }

... and here are my nodes (copied from readme.md):

>     nodes = [
>         {
>           id: "1",
>           text: "A",
>           link: ["-- yes -->", "-- no -->"],
>           next: ["2", "3"],
>           editable: true
>         },
>         { id: "2", text: "B" },
>         { id: "3", text: "C"}
>       ]
>     }

I also restarted my vue dev server multiple times but nothing changed :-(

**Comment by useo6** [comment]
@robin1liu The issue persists even in 0.0.12. I think you forgot to rebuild the dist-file because when I change the "main" property of the package.json of vue-mermaid to "main": "src/index.js" it works in 0.0.12. So, can you rebuild/update the dist-file?
