### ISSUE TITLE
Add support to specify different link types from one node

### ISSUE THREAD

**Issue by JoshuaeKaiser** [robin1liu/vue-mermaid#2]
You can specify the link type, but if your child "next" nodes are an array it would be useful to specify the link type to each individual child. Maybe make the link and array of types whose with the index of each type atributing that type to each element in the next array if they have the same index.

**Comment by via4e** [comment]
![image](https://user-images.githubusercontent.com/19588975/67561896-5b0e6a00-f726-11e9-91a1-ffa8f1d67d62.png)
support the question, need the ability to do this

**Comment by robin1liu** [comment]
support at 0.0.12
